---
- hosts: webservers
  become: yes
  tasks:
  - name: Install php on ubuntu node
    apt:
     name: "{{myphppackageforubuntu}}"
     state: present
    when: ansible_os_family =="Debian"
  - name: Install php on redhat node
    yum:
     name: "{{myphppackageforredhat}}"
     state: present
    when: ansible_os_family =="RedHat"