---
- hosts: 172.31.43.55
  become: yes
  tasks:
  - name: i want to execute linux command directly
    command: hostname
    register: myresult
  - name: i want to display myresule
    debug: 
      msg: "{{myresult}}"