---
- hosts: 172.31.43.55
  become: yes
  tasks: 
  - name: i want to install git
    apt:
     name: git
     states: present
  
  - name: i want to install tree
    apt:
     name: tree
     state: present
  
  - name: i want to install php
    apt:
      name: php
      state: present
  


