---
- hosts: 172.31.43.55
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: i want to install websever on ubuntu node
    apt:
     name: apache2
     state: present
  - name: i want to server on ubuntu node
    service:
      name: apache2
      state: started

  - nmae: i want to copy myindex.j2 into node side
    template:
      src: myindex.j2
      dest: /var/www/index.html