---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver on debian node only
    apt: 
     name: apache2
     state: present
  
  
  - name: install webserver on redHat node only
    yum:
     name: httpd
     state: present
    
  
